"""Generate the published site: three channel feeds, archives, and the pages.

    uv run python scripts/generate_feed.py --out-dir _site
    uv run python scripts/generate_feed.py --out-dir _site --channel edge

Reads `registry/*.toml` plus the locks, and for each member: resolves the wheel
URL from the PyPI JSON API, downloads it, unzips it, reads the `haybale.toml`
inside, and builds a row. Every field comes from that artifact.

**This script never imports a downloaded package.** It runs in the privileged
tier — the one with `contents: write` that deploys Pages — so it must have no
reason to execute submitted code. Reading metadata out of a wheel is unzipping;
that is what makes the split possible. The load gate that *does* import lives
in `verify.yml`, which has `permissions: {}` and no secrets.

Output under `--out-dir`:

    index.html                              the three channels, what each asserts
    edge/marketplace.toml
    latest/marketplace.toml
    stable/marketplace.toml
    stable/<curation-tag>/marketplace.toml  immutable archive
    latest/<curation-tag>/marketplace.toml  immutable archive
    archives.html                           the archive index
    stable-report.md                        copied from the repo root when present
"""

from __future__ import annotations

import argparse
import shutil
import sys
import tempfile
from dataclasses import dataclass
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from emit import emit_feed  # noqa: E402
from haywire.core.library.haybale import Haybale  # noqa: E402
from marketplace_lib import (  # noqa: E402
    CHANNELS,
    Lock,
    MarketplaceError,
    RegistryEntry,
    build_row,
    download_wheel,
    fetch_all_releases,
    fetch_release,
    newest_version,
    read_lock,
    read_registry,
    read_wheel_metadata,
    verify_row_version,
)

BASE_URL = "https://going-haywire.github.io/marketplace"

_CHANNEL_BLURB = {
    "edge": "whatever is newest on PyPI right now. Regenerated nightly.",
    "latest": "the newest version of each library as of the last catalogue release, "
    "each proven to install and load on its own.",
    "stable": "versions proven to install and load *together* as one set. Advances when Haywire cuts a release.",
}

_FEED_HEADER = """\
# The Haywire curated marketplace — {channel} channel
#
# {blurb}
#
# Generated by scripts/generate_feed.py. Do not edit by hand: this file is
# rebuilt from registry/*.toml on every deploy and any edit is discarded.
#
# Subscribe by pasting this URL into Add Source in the studio's Library
# Browser:
#   {url}
#
# Every field in every row below was read out of the wheel it pins. Nothing
# here is authored by a curator. Being listed asserts that the distribution
# exists on PyPI, that this name maps to this distribution, and — for stable —
# that this version resolves alongside the rest of the set. It asserts nothing
# about whether the code is safe, correct, or maintained. Nobody reads the
# source.
"""


@dataclass(frozen=True)
class ChannelResult:
    """One generated channel: its rows, and what could not be built."""

    channel: str
    rows: list[Haybale]
    failures: list[tuple[str, str]]


def _resolve_version(entry: RegistryEntry, channel: str, lock: Lock | None) -> str:
    """Which version of *entry* this channel describes.

    `edge` tracks PyPI directly; the pinned channels take their answer from the
    lock and nowhere else, so a generated feed can never disagree with the set
    that was actually solved and verified.
    """
    if channel == "edge":
        return newest_version(fetch_all_releases(entry.name))
    if lock is None:
        raise MarketplaceError(f"channel {channel!r} needs a lock")
    version = lock.pins.get(entry.name)
    if not version:
        # Not an error: a library can be in the registry and legitimately not
        # in `stable` yet — it may have failed to fit. stable-report.md is
        # where that is explained.
        raise KeyError(entry.name)
    return version


def build_channel(
    entries: list[RegistryEntry],
    channel: str,
    lock: Lock | None,
    *,
    work_dir: Path,
) -> ChannelResult:
    """Build every row for one channel by reading each pinned wheel."""
    rows: list[Haybale] = []
    failures: list[tuple[str, str]] = []

    for entry in entries:
        try:
            version = _resolve_version(entry, channel, lock)
        except KeyError:
            continue  # Not in this channel's set; see stable-report.md.
        except MarketplaceError as exc:
            failures.append((entry.name, str(exc)))
            continue

        try:
            release = fetch_release(entry.name, version)
            if not release.wheel_url:
                raise MarketplaceError(
                    f"{entry.name} {version} has no wheel on PyPI. Row metadata is read out of "
                    f"a wheel; building an sdist to read it would mean executing its setup."
                )
            if release.yanked:
                raise MarketplaceError(
                    f"{entry.name} {version} is yanked"
                    + (f": {release.yanked_reason}" if release.yanked_reason else "")
                )
            wheel = download_wheel(release.wheel_url, work_dir / f"{entry.name}-{version}.whl")
            metadata = read_wheel_metadata(wheel, entry.name)
            if not metadata.declares_library_entry_point:
                raise MarketplaceError(
                    f"{entry.name} {version} declares no `haywire.libraries` entry point — "
                    f"a studio could install it but never load it."
                )
            row = build_row(metadata, dist_name=entry.name, version=version, channel=channel)
            verify_row_version(row, metadata)
            rows.append(row)
        except MarketplaceError as exc:
            failures.append((entry.name, str(exc)))

    return ChannelResult(channel=channel, rows=rows, failures=failures)


# ─────────────────────────────────────────────────────────────────────────────
# Pages
# ─────────────────────────────────────────────────────────────────────────────

_PAGE_CSS = """\
:root { color-scheme: light dark; }
body { font: 16px/1.6 system-ui, -apple-system, "Segoe UI", sans-serif;
       max-width: 46rem; margin: 0 auto; padding: 2rem 1.25rem 4rem; }
code, pre { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: .9em; }
pre { overflow-x: auto; padding: .75rem 1rem; border-radius: 6px;
      background: rgba(127,127,127,.12); }
table { border-collapse: collapse; width: 100%; margin: 1.5rem 0; display: block; overflow-x: auto; }
th, td { text-align: left; padding: .5rem .75rem; border-bottom: 1px solid rgba(127,127,127,.3);
         vertical-align: top; }
th { font-weight: 600; }
h1 { margin-bottom: .25rem; } h2 { margin-top: 2.5rem; }
.sub { opacity: .7; margin-top: 0; }
.warn { border-left: 3px solid #c93; padding: .5rem 0 .5rem 1rem; margin: 1.5rem 0; }
a { color: inherit; }
"""


def _html_escape(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")


def render_index(results: dict[str, ChannelResult]) -> str:
    """The landing page: the three channels and what each asserts."""
    rows = "\n".join(
        f"    <tr><td><strong>{channel}</strong></td>"
        f'<td><a href="{BASE_URL}/{channel}/marketplace.toml"><code>{channel}/marketplace.toml</code></a></td>'
        f"<td>{_html_escape(_CHANNEL_BLURB[channel])}</td>"
        f"<td>{len(results[channel].rows) if channel in results else '—'}</td></tr>"
        for channel in CHANNELS
    )
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>The Haywire curated marketplace</title>
<style>{_PAGE_CSS}</style></head><body>
<h1>The Haywire curated marketplace</h1>
<p class="sub">A curated catalogue of <a href="https://github.com/going-haywire/haywire">Haywire</a>
libraries, published as three subscribable feeds.</p>

<p>Paste one of these URLs into <strong>Add Source</strong> in the studio's Library
Browser, or edit <code>~/.haywire/db/haybale_marketplace/marketplace.toml</code>
directly. Do not subscribe to two channels at once — they offer the same
library names at different versions, and the studio treats that as a conflict
on every refresh.</p>

<table>
  <thead><tr><th>channel</th><th>URL</th><th>you get</th><th>libraries</th></tr></thead>
  <tbody>
{rows}
  </tbody>
</table>

<h2>What being listed means — and does not</h2>
<p>Merging a library into this catalogue asserts exactly three things:</p>
<ol>
  <li>The distribution exists on PyPI and its wheel contains a valid <code>haybale.toml</code>.</li>
  <li><strong>This name maps to this distribution</strong> — every row is generated by unzipping
      the wheel it points at, so it cannot describe one package and install another.</li>
  <li>For <code>stable</code> only: this version resolves alongside every other library in
      the set, and imports cleanly.</li>
</ol>
<div class="warn">
<p>It asserts <strong>nothing</strong> about whether the code is safe, correct, maintained,
or fit for your purpose. <strong>Nobody reads the source.</strong> Being listed here is not
a security review — evaluate a library exactly as you would any package you install
from PyPI.</p>
</div>

<h2>More</h2>
<ul>
  <li><a href="{BASE_URL}/archives.html">Archived catalogue releases</a> — every past
      <code>stable</code> and <code>latest</code> set, kept permanently.</li>
  <li><a href="{BASE_URL}/stable-report.md">stable-report.md</a> — why each library sits at
      the version it does.</li>
  <li><a href="https://github.com/going-haywire/marketplace">The repo</a> — how to get a
      library listed.</li>
</ul>
</body></html>
"""


@dataclass(frozen=True)
class ArchiveRecord:
    """One immutable archived set, as listed on `archives.html`."""

    tag: str
    channel: str
    generated: str
    framework: str
    library_count: int


def render_archives(records: list[ArchiveRecord]) -> str:
    """The archive index.

    Required, not polish: GitHub Pages serves no directory listings, so
    `/stable/` returns 404 unless an index exists there. Without this page a
    user would have to guess curation-tag names, and the archives could not be
    found or chosen between. Each row carries the tag, the date, the
    haywire-core version the set was solved against, and its library count —
    which is what makes one archive choosable over another.
    """
    if records:
        body = "\n".join(
            f"    <tr><td><code>{_html_escape(r.tag)}</code></td>"
            f"<td>{_html_escape(r.channel)}</td>"
            f"<td>{_html_escape(r.generated)}</td>"
            f"<td><code>{_html_escape(r.framework)}</code></td>"
            f"<td>{r.library_count}</td>"
            f'<td><a href="{BASE_URL}/{r.channel}/{_html_escape(r.tag)}/marketplace.toml">'
            f"marketplace.toml</a></td></tr>"
            for r in records
        )
        table = f"""<table>
  <thead><tr><th>tag</th><th>channel</th><th>date</th><th>haywire-core</th>
             <th>libraries</th><th>feed</th></tr></thead>
  <tbody>
{body}
  </tbody>
</table>"""
    else:
        table = "<p>No archives yet — the first curation tag will create one.</p>"

    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Archived catalogue releases</title>
<style>{_PAGE_CSS}</style></head><body>
<h1>Archived catalogue releases</h1>
<p class="sub"><a href="{BASE_URL}/">← the curated marketplace</a></p>

<p>Every <code>stable</code> and <code>latest</code> set ever published, kept permanently
at an immutable URL. Subscribe to one of these instead of the moving channel when you
need a set that will not change under you.</p>

{table}

<p>The moving channels are
<a href="{BASE_URL}/stable/marketplace.toml"><code>stable</code></a>,
<a href="{BASE_URL}/latest/marketplace.toml"><code>latest</code></a> and
<a href="{BASE_URL}/edge/marketplace.toml"><code>edge</code></a>.</p>
</body></html>
"""


def collect_archives(out_dir: Path) -> list[ArchiveRecord]:
    """Read the archives already on disk, so the index lists every one.

    Scanned from the output tree rather than tracked in a file: the deploy
    checks out the existing `gh-pages` branch, so what is on disk *is* the
    published history — and an index built from it cannot drift from what is
    actually served.
    """
    import re
    import tomllib

    records: list[ArchiveRecord] = []
    for channel in ("stable", "latest"):
        channel_dir = out_dir / channel
        if not channel_dir.is_dir():
            continue
        for tag_dir in sorted(channel_dir.iterdir(), reverse=True):
            feed = tag_dir / "marketplace.toml"
            if not tag_dir.is_dir() or not feed.is_file():
                continue
            text = feed.read_text(encoding="utf-8")
            count = len(tomllib.loads(text).get("haybales", []))
            meta = re.search(r"# archived: (\S+) (\S+) haywire-core=(\S+)", text)
            records.append(
                ArchiveRecord(
                    tag=tag_dir.name,
                    channel=channel,
                    generated=meta.group(2) if meta else "",
                    framework=meta.group(3) if meta else "",
                    library_count=count,
                )
            )
    return sorted(records, key=lambda r: (r.tag, r.channel), reverse=True)


# ─────────────────────────────────────────────────────────────────────────────


def generate(
    *,
    repo_root: Path,
    out_dir: Path,
    channels: tuple[str, ...],
    curation_tag: str = "",
) -> dict[str, ChannelResult]:
    """Build every requested channel and write the site into *out_dir*."""
    entries = read_registry(repo_root / "registry")
    if not entries:
        raise MarketplaceError(f"{repo_root / 'registry'} holds no entries — nothing to publish")

    locks: dict[str, Lock | None] = {"edge": None}
    for channel in ("stable", "latest"):
        if channel in channels:
            locks[channel] = read_lock(repo_root / "locks" / f"{channel}.toml")

    results: dict[str, ChannelResult] = {}
    out_dir.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory() as tmp:
        work_dir = Path(tmp)
        for channel in channels:
            lock = locks.get(channel)
            result = build_channel(entries, channel, lock, work_dir=work_dir)
            results[channel] = result

            header = _FEED_HEADER.format(
                channel=channel,
                blurb=_CHANNEL_BLURB[channel],
                url=f"{BASE_URL}/{channel}/marketplace.toml",
            )
            body = emit_feed(result.rows, header=header)

            channel_dir = out_dir / channel
            channel_dir.mkdir(parents=True, exist_ok=True)
            (channel_dir / "marketplace.toml").write_text(body, encoding="utf-8")

            # Archive the pinned channels under their curation tag. `edge` is
            # never archived: its specs float, so an "immutable" edge archive
            # would be a promise the channel cannot keep.
            if curation_tag and channel in ("stable", "latest") and lock is not None:
                stamp = (
                    f"# archived: {curation_tag} {date.today().isoformat()} "
                    f"haywire-core={lock.framework.get('haywire-core', 'unknown')}\n"
                )
                archive_dir = channel_dir / curation_tag
                archive_dir.mkdir(parents=True, exist_ok=True)
                (archive_dir / "marketplace.toml").write_text(stamp + body, encoding="utf-8")

    (out_dir / "index.html").write_text(render_index(results), encoding="utf-8")
    (out_dir / "archives.html").write_text(render_archives(collect_archives(out_dir)), encoding="utf-8")

    report = repo_root / "stable-report.md"
    if report.is_file():
        shutil.copyfile(report, out_dir / "stable-report.md")

    # Pages runs Jekyll by default, which drops files and directories whose
    # names begin with an underscore and can rewrite what it thinks is content.
    # Nothing here is a Jekyll site.
    (out_dir / ".nojekyll").write_text("", encoding="utf-8")

    return results


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="generate_feed",
        description="Generate the curated marketplace's published feeds and pages.",
    )
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parent.parent)
    parser.add_argument("--out-dir", type=Path, required=True)
    parser.add_argument(
        "--channel",
        action="append",
        choices=CHANNELS,
        help="Generate only this channel (repeatable). Default: all three.",
    )
    parser.add_argument(
        "--curation-tag",
        default="",
        help="Write immutable archives for stable/latest under this tag.",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Exit non-zero if any library failed to build a row (used by deploy).",
    )
    args = parser.parse_args(argv)

    channels = tuple(args.channel) if args.channel else CHANNELS

    try:
        results = generate(
            repo_root=args.repo_root,
            out_dir=args.out_dir,
            channels=channels,
            curation_tag=args.curation_tag,
        )
    except MarketplaceError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    failed = False
    for channel in channels:
        result = results[channel]
        print(f"{channel}: {len(result.rows)} rows -> {args.out_dir / channel / 'marketplace.toml'}", file=sys.stderr)
        for name, reason in result.failures:
            failed = True
            print(f"  ! {name}: {reason}", file=sys.stderr)

    return 1 if failed and args.strict else 0


if __name__ == "__main__":
    sys.exit(main())
